# Generated by Django 3.2.5 on 2021-07-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210715_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=20, verbose_name='isim')),
                ('comment_content', models.CharField(max_length=150, verbose_name='yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article.article', verbose_name='makale')),
            ],
        ),
    ]
